### ISSUE TITLE
Regexes with unescaped forward slashes are handled incorrectly

### ISSUE THREAD

**Issue by rarkins** [davisjam/safe-regex#20]
Hi, I observed some additional strings being rejected once upgrading to v2. Looking at the v2.0.0 release notes, it did not sound like this would be the case (I thought the changes were more under the hood). I am seeing strings like `^@types/query-string` being rejected so rolling back the upgrade. Can you shed any light on these changes and if they are expected? Thanks.

**Comment by davisjam** [comment]
Thanks for the bug report.

The root cause is as follows:
- I was sending strings to `regexp-tree` instead of regexes.
- `regexp-tree` strings need to have '/.../' so I was wrapping regexes-as-strings with forward slashes.
- If the string already contained an unescaped forward slash, then it would no longer be a valid regex, and parsing it would fail.
    - Example: `^abc/` --> `/^abc//`
- If `safe-regex` can't parse a regex, it returns `false`.

**Comment by davisjam** [comment]
@rarkins This is fixed in #21. Published to npm under v2.0.1.
