### ISSUE TITLE
Add code coverage check

### ISSUE THREAD

**Issue by davisjam** [davisjam/safe-regex#7]
Looks like [istanbul](https://stackoverflow.com/questions/16633246/code-coverage-with-mocha?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) is a good option with mocha.

**Comment by sverweij** [comment]
Hi @davisjam - I can pick this up if you want. 

The current tests are written in `tape` (which makes sense as substack's been involved with this). Does your statement mean you're open to using other test frameworks as well? If so, I'd like to propose to use jest:
- as the most recent one it's the framework that learnt the most from the others  
- because of its wide use it'll be familiar to a larger population of potential maintainers
- it has many batteries included, a.o. code coverage (although setting code up code coverage for the other frameworks is not super hard either).

(B.t.w. I'm familiar with tape, jasmine, mocha and jest - so if you have a preference for either I'm ball as well. Jest is great because of its built in batteries (like coverage). Mocha is cool as well because of its extensive infrastructure. Both are heavily used and depended upon (see [npm-stat](https://npm-stat.com/charts.html?package=jest&package=mocha&package=jasmine&package=tape&from=2018-09-28&to=2019-09-28) for a comparison between the four).

What do you think?

**Comment by davisjam** [comment]
I am open to anything but tape.

I welcome a PR to move this project to jasmine and introduce code coverage measures.

I'd prefer to have `npm run test` run the tests and report coverage simultaneously -- looks like that's achievable with jest's `--coverage`?

**Comment by sverweij** [comment]
PR coming up that updates to jest and adds coverage reports.

I see a _testling_ configuration in the package.json and a [link](https://ci.testling.com/substack/safe-regex) in the readme to test results on their server, but it hasn't run for almost six years (there's likely no web hook on the repo that triggers it). Is my assumption correct it's ok to remove it (because otherwise the jest (or jasmine or mocha) output would need some massaging to be compatible with the _tap_ format testling uses)?

**Comment by sverweij** [comment]
PR coming up that updates to jest and adds coverage reports.

I see a _testling_ configuration in the package.json and a [link](https://ci.testling.com/substack/safe-regex) in the readme to test results on their server, but it hasn't run for almost six years (there's likely no web hook on the repo that triggers it). Is my assumption correct it's ok to remove it?

**Comment by davisjam** [comment]
> I see a testling configuration in the package.json and a link in the readme to test results on their server, but it hasn't run for almost six years (there's likely no web hook on the repo that triggers it). Is my assumption correct it's ok to remove it?

Yes, you can remove the testling configuration (and update the README if you like).

I'd prefer to use only Travis and worry about testing on Node.js. At this point I think the front-end JS situation is much more consistent than when the project was started.

**Comment by sverweij** [comment]
> Yes, you can remove the testling configuration (and update the README if you like).
good point - forgot that entirely :-)

Agree with your reasoning. Most FE js cross compiles with either babel or typescript down to something most browsers understand anyway.
